# Generated by Django 5.2 on 2025-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, max_length=15),
        ),
    ]
