# Generated by Django 5.2 on 2025-04-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.TextField(default='Something went wrong. Please try again.'),
        ),
    ]
